CREATE DATABASE IF NOT EXISTS ochoa

USE ochoa

CREATE TABLE ubicaciones (
    id INT(11) NOT NULL AUTO_INCREMENT
    nombre VARCHAR(250) DEFAULT NULL
)

DESCRIBE ubicaciones

INSERT INTO ubicaciones VALUES
(1,"CASA"),
(2,"EDIFICIO"),
(3,"Local"),